language: node_js
sudo: false
node_js:
  - '12'
branches:
  only:
    - master

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: '$GIT_TOKEN'
  local_dir: build
  on:
    branch: master
